title:            Coding Ventures
description:      Musings on technology and software development
logo:             logo.png
disqus_shortname: kkaratal
search:           true
#Change url to your domain. Leave localhost server or blank when working locally.
url:              http://codingventures.com

# Owner/author information
owner:
  name:           Kerem Karatal
  avatar:         bio-photo.jpg
  email:          you@email.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        keremk
  facebook:       
  github:         keremk
  stackexchange:  
  linkedin:       keremk
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics: UA-8158483-1  
google_verify: UA-8158483-1     
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Blog
    url: /articles
  - title: Portfolio
    url: /portfolio

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Los_Angeles
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

# kramdown:
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false

#   coderay:
#     coderay_line_numbers: 
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: class

include: [".htaccess"]
exclude: ["bin", "vendor", "lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
